#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
  # PRODUCTION SERVICES
  - name: production-web
    type: web
    env: static
    buildCommand: cd redwood && yarn install --frozen-lockfile && yarn rw deploy render web
    staticPublishPath: ./redwood/web/dist
    envVars:
      - key: NODE_VERSION
        value: 16
      - fromGroup: zorro-production
    routes:
      - type: rewrite
        source: /.redwood/functions/*
        destination: https://api.zorro.xyz/*
      - type: rewrite
        source: /*
        destination: /index.html
    domains:
      - zorro.xyz
    autoDeploy: false

  - name: production-api
    type: web
    env: node
    region: oregon
    buildCommand: cd redwood && yarn install --frozen-lockfile && yarn rw build api
    startCommand: cd redwood && yarn rw deploy render api
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: DATABASE_URL
        fromDatabase:
          name: production-db
          property: connectionString
      - fromGroup: zorro-production
    domains:
      - api.zorro.xyz
    autoDeploy: false

  # END PRODUCTION SERVICES

  # STAGING SERVICES
  - name: staging-web
    type: web
    env: static
    buildCommand: cd redwood && yarn install --frozen-lockfile && yarn rw deploy render web
    staticPublishPath: ./redwood/web/dist
    envVars:
      - key: NODE_VERSION
        value: 16
      - fromGroup: zorro-staging
    routes:
      - type: rewrite
        source: /.redwood/functions/*
        destination: https://staging-api.zorro.xyz/*
      - type: rewrite
        source: /*
        destination: /index.html
    domains:
      - testnet.zorro.xyz
    autoDeploy: false

  - name: staging-api
    type: web
    env: node
    region: oregon
    buildCommand: cd redwood && yarn install --frozen-lockfile && yarn rw build api
    startCommand: cd redwood && yarn rw deploy render api
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: DATABASE_URL
        fromDatabase:
          name: staging-db
          property: connectionString
      - fromGroup: zorro-staging
    domains:
      - staging-api.zorro.xyz
    autoDeploy: false

  # END STAGING SERVICES

databases:
  - name: production-db
    region: oregon
  - name: staging-db
    region: oregon
